IyBOZXRsaWZ5IGNvbmZpZ3VyYXRpb24gZmlsZQojIGh0dHBzOi8vZG9jcy5u
ZXRsaWZ5LmNvbS9jb25maWd1cmUtYnVpbGRzL2ZpbGUtYmFzZWQtY29uZmln
dXJhdGlvbi8KCltidWlsZF0KICAjIERpcmVjdG9yeSB3aXRoIHRoZSBidWls
dCBzaXRlCiAgcHVibGlzaCA9ICIuIgogIAogICMgQ29tbWFuZHMgdG8gYnVp
bGQgdGhlIHNpdGUgKG5vbmUgZm9yIHN0YXRpYyBzaXRlcykKICBjb21tYW5k
ID0gIiIKICAKICAjIEVudmlyb25tZW50IHZhcmlhYmxlcwogIGVudmlyb25t
ZW50ID0geyBOT0RFX0VOViA9ICJwcm9kdWN0aW9uIiB9CgojIEhlYWRlcnMg
Zm9yIHNlY3VyaXR5IGFuZCBwZXJmb3JtYW5jZQpbW2hlYWRlcnNdXQogIGZv
ciA9ICIvKiIKICBbaGVhZGVycy52YWx1ZXNdCiAgICBYLUZyYW1lLU9wdGlv
bnMgPSAiREVOWSIKICAgIFgtWFNTLVByb3RlY3Rpb24gPSAiMTsgbW9kZT1i
bG9jayIKICAgIFgtQ29udGVudC1UeXBlLU9wdGlvbnMgPSAibm9zbmlmZiIK
ICAgIFJlZmVycmVyLVBvbGljeSA9ICJzdHJpY3Qtb3JpZ2luLXdoZW4tY3Jv
c3Mtb3JpZ2luIgogICAgQ29udGVudC1TZWN1cml0eS1Qb2xpY3kgPSAiZGVm
YXVsdC1zcmMgJ3NlbGYnOyBzY3JpcHQtc3JjICdzZWxmJyAndW5zYWZlLWlu
bGluZSc7IHN0eWxlLXNyYyAnc2VsZicgJ3Vuc2FmZS1pbmxpbmUnOyBpbWct
c3JjICdzZWxmJyBkYXRhOiBodHRwczo7IGZvbnQtc3JjICdzZWxmJyBkYXRh
OjsiCgojIFJlZGlyZWN0cyBmb3IgbWFpbnRlbmFuY2UgbW9kZSAodW5jb21t
ZW50IGlmIG5lZWRlZCkKI1tbcmVkaXJlY3RzXV0KIyAgZnJvbSA9ICIvKiIK
IyAgdG8gPSAiL21haW50ZW5hbmNlLmh0bWwiCiMgIHN0YXR1cyA9IDMwMgoj
ICBjb25kaXRpb25zID0ge1JvbGUgPSBbIm1haW50ZW5hbmNlIl19CgojIFJl
ZGlyZWN0cyBmb3IgY2xlYW4gVVJMcwpbW3JlZGlyZWN0c11dCiAgZnJvbSA9
ICIvaW5kZXguaHRtbCIKICB0byA9ICIvIgogIHN0YXR1cyA9IDMwMQoKIyA0
MDQgcGFnZQpbW3JlZGlyZWN0c11dCiAgZnJvbSA9ICIvKiIKICB0byA9ICIv
aW5kZXguaHRtbCIKICBzdGF0dXMgPSAyMDA=
